- hosts: target
  tasks:
    - name: Copy artifact
      ansible.builtin.copy:
        src: devops
        dest: /home/ubuntu/devops

    - name: Service template
      become: true
      template:
        src: devops.service.j2
        dest: /etc/systemd/system/devops.service

    - name: This command will change the working directory to somedir/
      ansible.builtin.shell:
        cmd: sudo chmod +x devops

    - name: Run devops with systemd
      become: true
      ansible.builtin.systemd:
        state: started
        name: devops